services:
  web:
    build:
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - "./src:/usr/src/app"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file:
      - .env
  database:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass

volumes:
  postgres_data: